![Final Lesson Exercise](images/Banner_FEX.png)

# Lesson #1: Introduction to Data Science
## Good chocolate - The 'flavors of cacao' dataset

<table  align='left' valign="top"><tr>
<td align='left'>
    <a title='Chocolate and cocoa beans'> <img width="400" src="./images/a-01-dark-chocolate.jpg" width="px" align='left' /></a>
</td>
<td align='left' style="vertical-align:top">
<div align='left' style="font-size:130%">
<h3>Lets ask some questions:</h3>
<ul align='left'>
<li>What makes a chocolate good?</li>
<li>Where does good chocolate come from?</li> 
<li>Do you know what characterizes good chocolate?</li> 
<li>Is darker chocolate better?</li>
<li>How influential is the type of beans used?</li>
<li>Is it the type of beans or their origin?</li>
<li>Is the company producing it a major factor?</li>
</ul></div></td>
</tr>
</table>

## About this assignment
In this assignment, you will explore a dataset on chocolates.<br/>

You will do so, using the pandas library, introduced in the lesson.

## Preceding Step - import modules (packages)
This step is necessary in order to use external packages. 

**Use the following libraries for the assignment, when needed**:

In [1]:
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# === CELL TYPE: IMPORTS AND SETUP 

import pandas as pd
import os # for testing use only

### 1. Loading the 'flavors of cacao' dataset

### Instructions
<u>method name</u>: <b>load_csv</b>
<pre>The following is expected:
--- Complete the 'load_csv' function to load the 'flavors of cacao' dataset 
    from the csv, located in the file_name parameter into a pandas dataframe
    and return the dataframe
</pre>

In [2]:
# 1.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run after implementation)
# === CODE TYPE: ANSWER 

def load_csv(file_name):
   # טעינת הקובץ לתוך משתנה (נהוג לקרוא לו df - קיצור של DataFrame)
    df = pd.read_csv(file_name)
    
    # החזרת הטבלה כדי שנוכל להשתמש בה בהמשך המטלה
    return df

In [3]:
# 1.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run after implementation)
# === CODE TYPE: SELF TESTING
# Use the following code to test your implementation:

file_name = 'data' + os.sep + 'flavors_of_cacao.csv'
df_cocoa = load_csv(file_name)


# הצגת 5 השורות הראשונות בטבלה
print(df_cocoa.head())

# בדיקת כמות השורות והעמודות שנטענו
print("\nShape of the dataset:", df_cocoa.shape)

  Company (Maker-if known) Specific Bean Origin or Bar Name   REF  \
0                 A. Morin                      Agua Grande  1876
1                 A. Morin                            Kpime  1676
2                 A. Morin                           Atsane  1676
3                 A. Morin                            Akata  1680
4                 A. Morin                           Quilla  1704

   Review Date Cocoa Percent Company Location  Rating Bean Type  \
0         2016           63%           France    3.75       NaN
1         2015           70%           France    2.75       NaN
2         2015           70%           France    3.00       NaN
3         2015           70%           France    3.50       NaN
4         2015           70%           France    3.50       NaN

  Broad Bean Origin
0          Sao Tome
1              Togo
2              Togo
3              Togo
4              Peru

Shape of the dataset: (1795, 9)

In [4]:
# 1.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run after implementation, if used)
# === CODE TYPE: SELF TESTING
# Add your additional tests here if needed:

###
### YOUR CODE HERE
###

In [5]:
# 1.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run only)
# === CODE TYPE: GRADED TEST 

print ("Part 1 - Test 1 (0.2 points) - Sanity")
print ("\t--->Testing the implementation of 'load_csv' ...")

file_name = 'data' + os.sep + 'flavors_of_cacao.csv'
try:
    df_chocolate = load_csv(file_name)
except Exception as e:
    print ('You probably have a syntax error, we got the following exception:')
    print (str(e))
    raise 
    
print ("Good Job!\nYou've passed the 1st test for the 'load_dataset' function implementation :-)")

Part 1 - Test 1 (0.2 points) - Sanity
	--->Testing the implementation of 'load_csv' ...
Good Job!
You've passed the 1st test for the 'load_dataset' function implementation :-)

In [6]:
# 1.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run only)
# === CODE TYPE: GRADED TEST 

print ("Part 1 - Test 2 (0.3 points)")
print ("\t---> - Testing the implementation of 'load_csv' ...")

# file_name = '.' + os.sep + 'data' + os.sep + 'flavors_of_cacao.csv'
file_name = 'data' + os.sep + 'flavors_of_cacao.csv'
try:
    df_chocolate = load_csv(file_name)
except Exception as e:
    print ('You probably have a syntax error, we got the following exception:')
    print (str(e))
    raise 
    
assert df_chocolate is not None, "You did not return an object from the 'load_csv' function, try again"
assert isinstance(df_chocolate, pd.DataFrame), "The object you returned is not a dataframe, try again"

print ("Good Job!\nYou've passed the 2nd test for the 'load_dataset' function implementation :-)")

Part 1 - Test 2 (0.3 points)
	---> - Testing the implementation of 'load_csv' ...
Good Job!
You've passed the 2nd test for the 'load_dataset' function implementation :-)

### 2. Get some information about the dataset (from the dataframe)
#### The dataset contains the following columns:
* Company (Maker-if known) - Name of the company manufacturing the bar
* Specific Bean Origin or Bar Name -  The specific geo-region of origin for the bar.
* REF - reference number
* Review Date - Year of publication of the review.
* Cocoa Percent - Cocoa percentage (darkness) of the chocolate bar being reviewed.
* Company Location - Manufacturer base country.
* Rating - The rating that the experts gave (5 is the best, 1 is the worst)
* Bean Type - The variety (breed) of bean used, if provided
* Broad Bean Origin - The broad geo-region of origin for the bean

#### 2.a. Obtain the number of rows

### Instructions
<u>method name</u>: <b>get_number_of_rows</b>
<pre>The following is expected:
--- Complete the 'get_num_of_rows' function to return the number of rows 
    in the pandas dataframe, given in the parameter 'dataframe'
</pre>

In [7]:
# 2.a.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run after implementation)
# === CODE TYPE: ANSWER 

def get_number_of_rows(dataframe):
   
 return len(dataframe)

In [8]:
# 2.a.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run after implementation)
# === CODE TYPE: SELF TESTING
# Use the following code to test your implementation:

file_name = 'data' + os.sep + 'flavors_of_cacao.csv'
df_cocoa = load_csv(file_name)
n_rows = get_number_of_rows(df_cocoa)
# הדפסת מספר השורות שחזר מהפונקציה
print("Number of rows in the dataset is:", n_rows)

Number of rows in the dataset is: 1795

In [9]:
# 2.a.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run after implementation, if used)
# === CODE TYPE: SELF TESTING
# Add your additional tests here if needed:

###
### YOUR CODE HERE
###

In [10]:
# 2.a.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run only)
# === CODE TYPE: GRADED TEST 

print ("Part 2.a. - Test 1 (0.2 points) - Sanity")
print ("\t--->Testing the implementation of 'get_number_of_rows' ...")

raise_exception=False
file_name = 'data' + os.sep + 'flavors_of_cacao.csv'
try:
    df_chocolate = load_csv(file_name)
except Exception as e:
    raise_exception=True
    print ("Cascading error: You probably have a syntax error, in a function you're depended on, we got the following exception:")
    print (str(e))
    ###
    ### AUTOGRADER TEST - DO NOT REMOVE
    ###
    if raise_exception:
        raise 

raise_exception=False
try:    
    num_of_rows = get_number_of_rows(df_chocolate)
except Exception as e:
    print ('You probably have a syntax error, we got the following exception:')
    print (str(e))
    raise 
    
print ("Good Job!\nYou've passed the 1st test for the 'get_number_of_rows' function implementation :-)")

Part 2.a. - Test 1 (0.2 points) - Sanity
	--->Testing the implementation of 'get_number_of_rows' ...
Good Job!
You've passed the 1st test for the 'get_number_of_rows' function implementation :-)

In [11]:
# 2.a.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run only)
# === CODE TYPE: GRADED TEST 

print ("Part 2.a. - Test 2 (0.2 points)")
print ("\t--->Testing the implementation of 'get_number_of_rows' ...")

raise_exception=False
file_name = 'data' + os.sep + 'flavors_of_cacao.csv'
try:
    df_chocolate = load_csv(file_name)
except Exception as e:
    raise_exception=True
    print ("Cascading error: You probably have a syntax error, in a function you're depended on, we got the following exception:")
    print (str(e))
    ###
    ### AUTOGRADER TEST - DO NOT REMOVE
    ###
    if raise_exception:
        raise 

raise_exception=False
try:
    num_of_rows = get_number_of_rows(df_chocolate)
    print ('Num of rows=%d' %(num_of_rows))
except Exception as e:
    print ('You probably have a syntax error, we got the following exception:')
    print (str(e))
    raise 
    
assert num_of_rows != 0, "The number of rows can't be 0"

print ("Good Job!\nYou've passed the 2nd test for the 'get_number_of_rows' function implementation :-)")

Part 2.a. - Test 2 (0.2 points)
	--->Testing the implementation of 'get_number_of_rows' ...
Num of rows=1795
Good Job!
You've passed the 2nd test for the 'get_number_of_rows' function implementation :-)

#### 2.b. Obtain the number of columns

### Instructions
<u>method name</u>: <b>get_number_of_columns</b>
<pre>The following is expected:
--- Complete the 'get_num_of_columns' function to return the number of columns 
    in the pandas dataframe, given in the parameter 'dataframe'
</pre>

In [12]:
# 2.b.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run after implementation)
# === CODE TYPE: ANSWER 

def get_number_of_columns(dataframe):
    return dataframe.shape[1]

In [13]:
# 2.b.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run after implementation)
# === CODE TYPE: SELF TESTING
# Use the following code to test your implementation:

file_name = 'data' + os.sep + 'flavors_of_cacao.csv'
df_cocoa = load_csv(file_name)
n_cols = get_number_of_columns(df_cocoa)
# הדפסת מספר העמודות שחזר מהפונקציה
print("Number of columns in the dataset is:", n_cols)

Number of columns in the dataset is: 9

In [14]:
# 2.b.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run after implementation, if used)
# === CODE TYPE: SELF TESTING
# Add your additional tests here if needed:

print(df_cocoa.columns.tolist())

['Company (Maker-if known)', 'Specific Bean Origin or Bar Name', 'REF', 'Review Date', 'Cocoa Percent', 'Company Location', 'Rating', 'Bean Type', 'Broad Bean Origin']

In [15]:
# 2.b.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run only)
# === CODE TYPE: GRADED TEST 

print ("Part 2.b. - Test 1 (0.2 points) - Sanity")
print ("\t--->Testing the implementation of 'get_number_of_columns' ...")

raise_exception=False
file_name = 'data' + os.sep + 'flavors_of_cacao.csv'
try:
    df_chocolate = load_csv(file_name)
except Exception as e:
    raise_exception=True
    print ("Cascading error: You probably have a syntax error, in a function you're depended on, we got the following exception:")
    print (str(e))
    ###
    ### AUTOGRADER TEST - DO NOT REMOVE
    ###
    if raise_exception:
        raise 

raise_exception=False
try:
    num_of_columns = get_number_of_columns(df_chocolate)
except Exception as e:
    print ('You probably have a syntax error, we got the following exception:')
    print (str(e))
    raise 
    
print ("Good Job!\nYou've passed the 1st test for the 'get_number_of_columns' function implementation :-)")

Part 2.b. - Test 1 (0.2 points) - Sanity
	--->Testing the implementation of 'get_number_of_columns' ...
Good Job!
You've passed the 1st test for the 'get_number_of_columns' function implementation :-)

In [16]:
# 2.b.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run only)
# === CODE TYPE: GRADED TEST 

print ("Part 2.b. - Test 2 (0.2 points)")
print ("\t--->Testing the implementation of 'get_number_of_columns' ...")

raise_exception=False
file_name = 'data' + os.sep + 'flavors_of_cacao.csv'
try:
    df_chocolate = load_csv(file_name)
except Exception as e:
    raise_exception=True
    print ("Cascading error: You probably have a syntax error, in a function you're depended on, we got the following exception:")
    print (str(e))
    ###
    ### AUTOGRADER TEST - DO NOT REMOVE
    ###
    if raise_exception:
        raise 

raise_exception=False
try:
    num_of_columns = get_number_of_columns(df_chocolate)
    print ('Num of columns=%d' %(num_of_columns))
except Exception as e:
    print ('You probably have a syntax error, we got the following exception:')
    print (str(e))
    raise 
    
assert num_of_columns!=0, "The number of columns can't be 0"

print ("Good Job!\nYou've passed the 2nd test for the 'get_number_of_columns' function implementation :-)")

Part 2.b. - Test 2 (0.2 points)
	--->Testing the implementation of 'get_number_of_columns' ...
Num of columns=9
Good Job!
You've passed the 2nd test for the 'get_number_of_columns' function implementation :-)

In [17]:
# 2.b.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run only)
# === CODE TYPE: GRADED TEST 

print ("Part 2.b. - Test 3 (0.2 points)")
print ("\t--->Testing the implementation of 'get_number_of_rows' and 'get_number_of_columns' ...")

raise_exception=False
file_name = 'data' + os.sep + 'flavors_of_cacao.csv'
try:
    df_chocolate = load_csv(file_name)
except Exception as e:
    raise_exception=True
    print ("Cascading error: You probably have a syntax error, in a function you're depended on, we got the following exception:")
    print (str(e))
    ###
    ### AUTOGRADER TEST - DO NOT REMOVE
    ###
    if raise_exception:
        raise 

raise_exception=False
try:
    num_of_rows    = get_number_of_rows(df_chocolate)
    num_of_columns = get_number_of_columns(df_chocolate)
    print ('Num of rows=%d' %(num_of_rows))
    print ('Num of columns=%d' %(num_of_columns))
except Exception as e:
    print ('You probably have a syntax error, we got the following exception:')
    print (str(e))
    raise 
    
assert 4 == num_of_rows % num_of_columns, "You've got a wrong number of rows or columns"

print ("Good Job!\nYou've passed the 3rd test for the 'get_number_of_columns' function implementation :-)")

Part 2.b. - Test 3 (0.2 points)
	--->Testing the implementation of 'get_number_of_rows' and 'get_number_of_columns' ...
Num of rows=1795
Num of columns=9
Good Job!
You've passed the 3rd test for the 'get_number_of_columns' function implementation :-)

### 3. Reading information from the dataframe:

#### 3.a. Get rows in range

### Instructions
<u>method name</u>: <b>get_rows_in_range</b>
<pre>The following is expected:
--- Complete the 'get_rows_in_range' function to return only the rows 
    in a pandas dataframe, given in the parameter 'dataframe', within the
    range 'first_row' and 'last_row' (last row is excluded)
</pre>

In [18]:
# 3.a.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run after implementation)
# === CODE TYPE: ANSWER 

def get_rows_in_range(dataframe, first_row, last_row):
    # מחזיר את השורות מהאינדקס הראשון עד (ולא כולל) האינדקס האחרון
    return dataframe[first_row:last_row]

In [19]:
# 3.a.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run after implementation)
# === CODE TYPE: SELF TESTING
# Use the following code to test your implementation:

file_name = 'data' + os.sep + 'flavors_of_cacao.csv'
df_cocoa = load_csv(file_name)
row_begin_range, row_end_range = 1310, 1320
df_rows_in_range = get_rows_in_range(df_cocoa, row_begin_range, row_end_range)
# הדפסת הטווח שקיבלנו
print("The rows in range (1310 to 1320) are:")
print(df_rows_in_range)

# בדיקה נוספת - כמה שורות יש בתוצאה? (צריך להיות 10)
print("\nNumber of rows in the result:", len(df_rows_in_range))

The rows in range (1310 to 1320) are:
     Company (Maker-if known) Specific Bean Origin or Bar Name   REF  \
1310                  Potomac                  Upala, Batch 18   654
1311                  Potomac  San Martin, Amazonian Highlands   789
1312                  Potomac                            Bahia   789
1313                  Potomac                  Upala, Batch 12   607
1314                   Pralus                             Peru  1446
1315                   Pralus  Porcelana, S. of Lake Maracaibo   717
1316                   Pralus                            Chuao   486
1317                   Pralus                          Cuyagua   451
1318                   Pralus                        Papouasie   199
1319                   Pralus        Sambirano Valley, Le 100%   202

      Review Date Cocoa Percent Company Location  Rating            Bean Type  \
1310         2011           70%           U.S.A.    3.00               Matina
1311         2011           70%           U.S.A.    2.75                  NaN
1312         2011           70%           U.S.A.    3.50                  NaN
1313         2010           82%           U.S.A.    3.75               Matina
1314         2015           75%           France    3.25                  NaN
1315         2011           75%           France    3.25  Criollo (Porcelana)
1316         2010           75%           France    3.50           Trinitario
1317         2009           75%           France    2.00                  NaN
1318         2008           75%           France    3.00           Trinitario
1319         2008          100%           France    3.00              Criollo

     Broad Bean Origin
1310        Costa Rica
1311              Peru
1312            Brazil
1313        Costa Rica
1314              Peru
1315         Venezuela
1316         Venezuela
1317         Venezuela
1318  Papua New Guinea
1319        Madagascar

Number of rows in the result: 10

In [20]:
# 3.a.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run after implementation, if used)
# === CODE TYPE: SELF TESTING
# Add your additional tests here if needed:

###
### YOUR CODE HERE
###

In [21]:
# 3.a.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run only)
# === CODE TYPE: GRADED TEST 

print ("Part 3.a. - Test 1 (0.2 points) - Sanity")
print ("\t--->Testing the implementation of 'get_rows_in_range' ...")

raise_exception=False
file_name = 'data' + os.sep + 'flavors_of_cacao.csv'
try:
    df_chocolate = load_csv(file_name)
except Exception as e:
    raise_exception=True
    print ("Cascading error: You probably have a syntax error, in a function you're depended on, we got the following exception:")
    print (str(e))
    ###
    ### AUTOGRADER TEST - DO NOT REMOVE
    ###
    if raise_exception:
        raise 

raise_exception=False        
try:
    df_ranged_rows = get_rows_in_range(df_chocolate, 1310, 1320)
except Exception as e:
    print ('You probably have a syntax error, we got the following exception:')
    print (str(e))
    raise 
    
print ("Good Job!\nYou've passed the 1st test for the 'get_rows_in_range' function implementation :-)")

Part 3.a. - Test 1 (0.2 points) - Sanity
	--->Testing the implementation of 'get_rows_in_range' ...
Good Job!
You've passed the 1st test for the 'get_rows_in_range' function implementation :-)

In [22]:
# 3.a.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run only)
# === CODE TYPE: GRADED TEST 

print ("Part 3.a. - Test 2 (0.5 points)")
print ("\t--->Testing the implementation of 'get_rows_in_range' ...")

raise_exception=False
file_name = 'data' + os.sep + 'flavors_of_cacao.csv'
try:
    df_chocolate = load_csv(file_name)
except Exception as e:
    raise_exception=True
    print ("Cascading error: You probably have a syntax error, in a function you're depended on, we got the following exception:")
    print (str(e))
    ###
    ### AUTOGRADER TEST - DO NOT REMOVE
    ###
    if raise_exception:
        raise 

raise_exception=False       
try:
    df_ranged_rows = get_rows_in_range(df_chocolate, 1310, 1320)
except Exception as e:
    print ('You probably have a syntax error, we got the following exception:')
    print (str(e))
    raise 
        
try:
    num_of_rows    = get_number_of_rows(df_ranged_rows)
    num_of_columns = get_number_of_columns(df_ranged_rows)
    print ('Num of rows=%d' %(num_of_rows))
    print ('Num of columns=%d' %(num_of_columns))
except Exception as e:
    raise_exception=True
    print ("Cascading error: You probably have a syntax error, in a function you're depended on, we got the following exception:")
    print (str(e))
    ###
    ### AUTOGRADER TEST - DO NOT REMOVE
    ###
    if raise_exception:
        raise 
    
raise_exception=False  
assert num_of_rows==10 and num_of_columns==9, "Wrong number of rows or columns"

print ("Good Job!\nYou've passed the 2nd test for the 'get_rows_in_range' function implementation :-)")

print ('\nSub dataframe:')
df_ranged_rows

Part 3.a. - Test 2 (0.5 points)
	--->Testing the implementation of 'get_rows_in_range' ...
Num of rows=10
Num of columns=9
Good Job!
You've passed the 2nd test for the 'get_rows_in_range' function implementation :-)

Sub dataframe:

,Company (Maker-if known),Specific Bean Origin or Bar Name,REF,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin
1310,Potomac,"Upala, Batch 18",654,2011,70%,U.S.A.,3.00,Matina,Costa Rica
1311,Potomac,"San Martin, Amazonian Highlands",789,2011,70%,U.S.A.,2.75,NaN,Peru
1312,Potomac,Bahia,789,2011,70%,U.S.A.,3.50,NaN,Brazil
1313,Potomac,"Upala, Batch 12",607,2010,82%,U.S.A.,3.75,Matina,Costa Rica
1314,Pralus,Peru,1446,2015,75%,France,3.25,NaN,Peru
1315,Pralus,"Porcelana, S. of Lake Maracaibo",717,2011,75%,France,3.25,Criollo (Porcelana),Venezuela
1316,Pralus,Chuao,486,2010,75%,France,3.50,Trinitario,Venezuela
1317,Pralus,Cuyagua,451,2009,75%,France,2.00,NaN,Venezuela
1318,Pralus,Papouasie,199,2008,75%,France,3.00,Trinitario,Papua New Guinea
1319,Pralus,"Sambirano Valley, Le 100%",202,2008,100%,France,3.00,Criollo,Madagascar

#### 3.b. Get columns in range

### Instructions
<u>method name</u>: <b>get_columns_in_range</b>
<pre>The following is expected:
--- Complete the 'get_columns_in_range' function to return only the columns 
    in a pandas dataframe, given in the parameter 'dataframe', within the
    range 'first_column' and 'last_column' (last column is excluded)
</pre>

In [23]:
# 3.b.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run after implementation)
# === CODE TYPE: ANSWER 

def get_columns_in_range(dataframe, first_column, last_column):
   # מחזיר את כל השורות (:) ורק את העמודות בטווח המבוקש
    return dataframe.iloc[:, first_column:last_column]

In [24]:
# 3.b.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run after implementation)
# === CODE TYPE: SELF TESTING
# Use the following code to test your implementation:

file_name = 'data' + os.sep + 'flavors_of_cacao.csv'
df_cocoa = load_csv(file_name)
row_begin_range, row_end_range = 1310, 1320
df_rows_in_range = get_rows_in_range(df_cocoa, row_begin_range, row_end_range)
col_begin_range, col_end_range = 4, 6
df_cols_in_ranged = get_columns_in_range(df_rows_in_range, col_begin_range, col_end_range)
# נדפיס את התוצאה הסופית - צריכות להיות 10 שורות ו-2 עמודות
print("The sliced dataframe (rows 1310-1319, columns 4-5):")
print(df_cols_in_ranged)

# בדיקת מימדים (צריך להיות 10 שורות ו-2 עמודות)
print("\nShape of the result:", df_cols_in_ranged.shape)

The sliced dataframe (rows 1310-1319, columns 4-5):
     Cocoa Percent Company Location
1310           70%           U.S.A.
1311           70%           U.S.A.
1312           70%           U.S.A.
1313           82%           U.S.A.
1314           75%           France
1315           75%           France
1316           75%           France
1317           75%           France
1318           75%           France
1319          100%           France

Shape of the result: (10, 2)

In [25]:
# 3.b.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run after implementation, if used)
# === CODE TYPE: SELF TESTING
# Add your additional tests here if needed:

###
### YOUR CODE HERE
###

In [26]:
# 3.b.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run only)
# === CODE TYPE: GRADED TEST 

print ("Part 3.b. - Test 1 (0.2 points) - Sanity")
print ("\t--->Testing the implementation of 'get_columns_in_range' ...")

raise_exception=False
file_name = 'data' + os.sep + 'flavors_of_cacao.csv'
try:
    df_chocolate = load_csv(file_name)
except Exception as e:
    raise_exception=True
    print ("Cascading error: You probably have a syntax error, in a function you're depended on, we got the following exception:")
    print (str(e))
    ###
    ### AUTOGRADER TEST - DO NOT REMOVE
    ###
    if raise_exception:
        raise 

raise_exception=False        
try:
    df_ranged = get_columns_in_range(df_chocolate, 4, 6)
except Exception as e:
    print ('You probably have a syntax error, we got the following exception:')
    print (str(e))
    raise 
    
print ("Good Job!\nYou've passed the 1st test for the 'get_columns_in_range' function implementation :-)")

Part 3.b. - Test 1 (0.2 points) - Sanity
	--->Testing the implementation of 'get_columns_in_range' ...
Good Job!
You've passed the 1st test for the 'get_columns_in_range' function implementation :-)

In [27]:
# 3.b.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run only)
# === CODE TYPE: GRADED TEST 

print ("Part 3.b. - Test 2 (0.5 points)")
print ("\t--->Testing the implementation of 'get_columns_in_range' ...")

raise_exception=False
file_name = 'data' + os.sep + 'flavors_of_cacao.csv'
try:
    df_chocolate = load_csv(file_name)
except Exception as e:
    raise_exception=True
    print ("Cascading error: You probably have a syntax error, in a function you're depended on, we got the following exception:")
    print (str(e))
    ###
    ### AUTOGRADER TEST - DO NOT REMOVE
    ###
    if raise_exception:
        raise 

raise_exception=False        
try:
    df_ranged = get_columns_in_range(df_chocolate, 4, 6)
except Exception as e:
    print ('You probably have a syntax error, we got the following exception:')
    print (str(e))
    raise 
        
try:
    num_of_rows    = get_number_of_rows(df_ranged)
    num_of_columns = get_number_of_columns(df_ranged)
    print ('Num of rows=%d' %(num_of_rows))
    print ('Num of columns=%d' %(num_of_columns))
except Exception as e:
    raise_exception=True
    print ("Cascading error: You probably have a syntax error, in a function you're depended on, we got the following exception:")
    print (str(e))
    ###
    ### AUTOGRADER TEST - DO NOT REMOVE
    ###
    if raise_exception:
        raise 
    
raise_exception=False  
assert num_of_columns==2, "Wrong number of columns"

print ("Good Job!\nYou've passed the 2nd test for the 'get_columns_in_range' function implementation :-)")   

print ('\nSub dataframe:')
df_ranged

Part 3.b. - Test 2 (0.5 points)
	--->Testing the implementation of 'get_columns_in_range' ...
Num of rows=1795
Num of columns=2
Good Job!
You've passed the 2nd test for the 'get_columns_in_range' function implementation :-)

Sub dataframe:

     Cocoa Percent Company Location
0              63%           France
1              70%           France
2              70%           France
3              70%           France
4              70%           France
...            ...              ...
1790           70%          Austria
1791           65%          Austria
1792           65%          Austria
1793           62%          Austria
1794           65%          Austria

[1795 rows x 2 columns]

In [28]:
# 3.b.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run only)
# === CODE TYPE: GRADED TEST 

print ("Part 3.b. - Test 3 (0.6 points)")
print ("\t--->Testing the implementation of 'get_columns_in_range' ...")

raise_exception=False
file_name = 'data' + os.sep + 'flavors_of_cacao.csv'
try:
    df_chocolate = load_csv(file_name)
except Exception as e:
    raise_exception=True
    print ("Cascading error: You probably have a syntax error, in a function you're depended on, we got the following exception:")
    print (str(e))
    ###
    ### AUTOGRADER TEST - DO NOT REMOVE
    ###
    if raise_exception:
        raise 
        
raise_exception=False
try:
    df_ranged_rows = get_rows_in_range(df_chocolate, 1310, 1320)
    df_ranged = get_columns_in_range(df_ranged_rows, 4, 6)
except Exception as e:
    print ('You probably have a syntax error, we got the following exception:')
    print (str(e))
    raise 
    
try:
    num_of_rows    = get_number_of_rows(df_ranged)
    num_of_columns = get_number_of_columns(df_ranged)
    print ('Num of rows=%d' %(num_of_rows))
    print ('Num of columns=%d' %(num_of_columns))
except Exception as e:
    raise_exception=True
    print ("Cascading error: You probably have a syntax error, in a function you're depended on, we got the following exception:")
    print (str(e))
    ###
    ### AUTOGRADER TEST - DO NOT REMOVE
    ###
    if raise_exception:
        raise 
    
raise_exception=False  
    
assert num_of_rows==10 and num_of_columns==2, "Wrong number of rows or columns"

print ("Good Job!\nYou've passed the 3rd test for the 'get_columns_in_range' function implementation :-)")   

print ('\nSub dataframe:')
df_ranged

Part 3.b. - Test 3 (0.6 points)
	--->Testing the implementation of 'get_columns_in_range' ...
Num of rows=10
Num of columns=2
Good Job!
You've passed the 3rd test for the 'get_columns_in_range' function implementation :-)

Sub dataframe:

     Cocoa Percent Company Location
1310           70%           U.S.A.
1311           70%           U.S.A.
1312           70%           U.S.A.
1313           82%           U.S.A.
1314           75%           France
1315           75%           France
1316           75%           France
1317           75%           France
1318           75%           France
1319          100%           France

### 4. Conditional Selection of data:

#### 4.a. Select rows by cell value

### Instructions
<u>method name</u>: <b>select_rows_by_cell_val</b>
<pre>The following is expected:
--- Complete the 'select_rows_by_cell_val' function to return only the rows 
    in a pandas dataframe, given in the parameter 'dataframe', which 
    match the 'matching_val' value of in the cell in the 'col_name' column.
</pre>

In [29]:
# 4.a.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run after implementation)
# === CODE TYPE: ANSWER 

def select_rows_by_cell_val(dataframe, col_name, matching_val):
  # מחזיר את כל השורות שבהן הערך בעמודה col_name שווה ל-matching_val
    return dataframe[dataframe[col_name] == matching_val]

In [30]:
# 4.a.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run after implementation)
# === CODE TYPE: SELF TESTING
# Use the following code to test your implementation:

file_name = 'data' + os.sep + 'flavors_of_cacao.csv'
df_cocoa = load_csv(file_name)
col_name_1, col_val_1 = 'Bean Type', 'Forastero'
col_name_3, col_val_3 = 'Cocoa Percent', '100%'
df_rows_pass_cond_1 = select_rows_by_cell_val(df_cocoa, col_name_1, col_val_1)
df_rows_pass_cond_1_3 = select_rows_by_cell_val(df_rows_pass_cond_1, col_name_3, col_val_3)
# הדפסת השורות שעברו את שני התנאים
print("Chocolates that are Forastero AND 100% cocoa:")
print(df_rows_pass_cond_1_3)

# בדיקה כמה שוקולדים כאלו מצאנו
print("\nNumber of matching rows:", len(df_rows_pass_cond_1_3))

Chocolates that are Forastero AND 100% cocoa:
    Company (Maker-if known) Specific Bean Origin or Bar Name  REF  \
437          Claudio Corallo                         Principe  252

     Review Date Cocoa Percent Company Location  Rating  Bean Type  \
437         2008          100%         Sao Tome     1.0  Forastero

       Broad Bean Origin
437  Sao Tome & Principe

Number of matching rows: 1

In [31]:
# 4.a.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run after implementation, if used)
# === CODE TYPE: SELF TESTING
# Add your additional tests here if needed:

###
### YOUR CODE HERE
###

In [32]:
# 4.a.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run only)
# === CODE TYPE: GRADED TEST 

print ("Part 4.a. - Test 1 (0.2 points) - Sanity")
print ("\t--->Testing the implementation of 'select_rows_by_cell_val' ...\n")

raise_exception=False
file_name = 'data' + os.sep + 'flavors_of_cacao.csv'
try:
    df_chocolate = load_csv(file_name)
except Exception as e:
    raise_exception=True
    print ("Cascading error: You probably have a syntax error, in a function you're depended on, we got the following exception:")
    print (str(e))
    ###
    ### AUTOGRADER TEST - DO NOT REMOVE
    ###
    if raise_exception:
        raise 

raise_exception=False        
try:
    df_passes_cond_1 = select_rows_by_cell_val(df_chocolate, 'Bean Type', 'Forastero')
except Exception as e:
    print ('You probably have a syntax error, we got the following exception:')
    print (str(e))
    raise 

print ("Good Job!\nYou've passed the 1st test for the 'select_rows_by_cell_val' function implementation :-)")

Part 4.a. - Test 1 (0.2 points) - Sanity
	--->Testing the implementation of 'select_rows_by_cell_val' ...

Good Job!
You've passed the 1st test for the 'select_rows_by_cell_val' function implementation :-)

In [33]:
# 4.a.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run only)
# === CODE TYPE: GRADED TEST 

print ("Part 4.a. - Test 2 (0.5 points)")
print ("\t--->Testing the implementation of 'select_rows_by_cell_val' ...\n")

raise_exception=False
file_name = 'data' + os.sep + 'flavors_of_cacao.csv'
try:
    df_chocolate = load_csv(file_name)
    df_passes_cond_1 = select_rows_by_cell_val(df_chocolate, 'Bean Type', 'Forastero')
except Exception as e:
    print ('You probably have a syntax error, we got the following exception:')
    print (str(e))
    raise 
        
try:
    num_of_rows    = get_number_of_rows(df_passes_cond_1)
    num_of_columns = get_number_of_columns(df_passes_cond_1)
    print ('Num of rows=%d' %(num_of_rows))
    print ('Num of columns=%d' %(num_of_columns))
except Exception as e:
    raise_exception=True
    print ("Cascading error: You probably have a syntax error, in a function you're depended on, we got the following exception:")
    print (str(e))
    ###
    ### AUTOGRADER TEST - DO NOT REMOVE
    ###
    if raise_exception:
        raise 
    
raise_exception=False  
    
assert num_of_rows==87 and num_of_columns==9, "Wrong number of rows or columns"

print ("Good Job!\nYou've passed the 2nd test for the 'select_rows_by_cell_val' function implementation :-)")   

print ('First few rows of the dataframe passing 1st condition:')
df_passes_cond_1.head()

Part 4.a. - Test 2 (0.5 points)
	--->Testing the implementation of 'select_rows_by_cell_val' ...

Num of rows=87
Num of columns=9
Good Job!
You've passed the 2nd test for the 'select_rows_by_cell_val' function implementation :-)
First few rows of the dataframe passing 1st condition:

,Company (Maker-if known),Specific Bean Origin or Bar Name,REF,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin
34,Akesson's (Pralus),"Monte Alegre, D. Badero",508,2010,75%,Switzerland,2.75,Forastero,Brazil
43,Alexandre,"Makwale Village, Kyela",1944,2017,70%,Netherlands,3.50,Forastero,Tanzania
63,Amatller (Simon Coll),Ghana,322,2009,70%,Spain,3.00,Forastero,Ghana
66,Amatller (Simon Coll),Ghana,464,2009,85%,Spain,3.00,Forastero,Ghana
136,Artisan du Chocolat,Congo,300,2008,72%,U.K.,3.75,Forastero,Congo

In [34]:
# 4.a.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run only)
# === CODE TYPE: GRADED TEST 

print ("Part 4.a. - Test 3 (0.5 points)")
print ("\t--->Testing the implementation of 'select_rows_by_cell_val'")
print ("\t\t====> Full grading test - the following test can not be seen before submission ...")

###
### AUTOGRADER TEST - DO NOT REMOVE
###

Part 4.a. - Test 3 (0.5 points)
	--->Testing the implementation of 'select_rows_by_cell_val'
		====> Full grading test - the following test can not be seen before submission ...

#### 4.b. Select rows with value in given range

### Instructions
<u>method name</u>: <b>select_rows_w_vals_in_range</b>
<pre>The following is expected:
--- Complete the 'select_rows_w_vals_in_range' function to return only the rows 
    in a pandas dataframe, given in the parameter 'dataframe', for which 
    the values of some column given in the 'col_name' parameter, are 
    between the 'lower_range' and 'higher_range' (inculding lower_range and higher_range)
</pre>

In [35]:
# 4.b.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run after implementation)
# === CODE TYPE: ANSWER 

def select_rows_w_vals_in_range(dataframe, col_name, lower_range, higher_range):
   # סינון שורות שבהן הערך בעמודה col_name נמצא בתוך הטווח (כולל הקצוות)
    return dataframe[dataframe[col_name].between(lower_range, higher_range)]

In [36]:
# 4.b.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run after implementation)
# === CODE TYPE: SELF TESTING
# Use the following code to test your implementation:

file_name = 'data' + os.sep + 'flavors_of_cacao.csv'
df_cocoa = load_csv(file_name)
col_name_1, col_val_1 = 'Bean Type', 'Forastero'
col_name_2, col_lower_val_2, col_upper_val_2 = 'Review Date', 2015, 2017
df_rows_pass_cond_1 = select_rows_by_cell_val(df_cocoa, col_name_1, col_val_1)
df_rows_pass_cond_1_2 = select_rows_w_vals_in_range(df_rows_pass_cond_1, col_name_2, col_lower_val_2, col_upper_val_2)
# הדפסת השורות שענו על שני התנאים
print("Forastero chocolates reviewed between 2015 and 2017:")
print(df_rows_pass_cond_1_2)

# בדיקה כמה שוקולדים כאלו מצאנו
print("\nNumber of matching rows:", len(df_rows_pass_cond_1_2))

# בונוס: נבדוק מה הערך המינימלי והמקסימלי בעמודת השנה כדי לוודא שהטווח תקין
if not df_rows_pass_cond_1_2.empty:
    print("Min year in results:", df_rows_pass_cond_1_2['Review Date'].min())
    print("Max year in results:", df_rows_pass_cond_1_2['Review Date'].max())

Forastero chocolates reviewed between 2015 and 2017:
     Company (Maker-if known) Specific Bean Origin or Bar Name   REF  \
43                  Alexandre           Makwale Village, Kyela  1944
403          Chocolate Makers               Congo, Gorilla bar  1530
521               De Villiers              Bundibugyo District  1832
729             Georgia Ramon                      ABOCFA Coop  1642
800               hello cocoa                           Uganda  1458
912                      K'ul            Bahia, Fazenda Camboa  1852
947        Laia aka Chat-Noir              Sao Tome, Batch 151  1638
1193                   Nuance                      Ghana, 2013  1454
1202                   Ocelot                          Virunga  1558
1281         Pierre Marcolini              Haut Penja, w/ nibs  1658
1357                    Raaka                          Virunga  1708
1447           Shark Mountain                 Papua New Guinea  1450
1474                 Sjolinds                            Ghana  1454
1622                     TCHO                      West Africa  1716

      Review Date Cocoa Percent Company Location  Rating  Bean Type  \
43           2017           70%      Netherlands    3.50  Forastero
403          2015           68%        Amsterdam    3.50  Forastero
521          2016           70%     South Africa    2.50  Forastero
729          2015           70%          Germany    4.00  Forastero
800          2015           57%           U.S.A.    2.75  Forastero
912          2016           70%           U.S.A.    3.75  Forastero
947          2015           75%           France    3.50  Forastero
1193         2015           70%           U.S.A.    3.75  Forastero
1202         2015           70%         Scotland    3.75  Forastero
1281         2015           70%          Belgium    3.25  Forastero
1357         2015           75%           U.S.A.    2.75  Forastero
1447         2015           73%           U.S.A.    3.50  Forastero
1474         2015           70%           U.S.A.    2.75  Forastero
1622         2016           62%           U.S.A.    2.00  Forastero

     Broad Bean Origin
43            Tanzania
403              Congo
521             Uganda
729              Ghana
800             Uganda
912             Brazil
947           Sao Tome
1193             Ghana
1202             Congo
1281          Cameroon
1357             Congo
1447  Papua New Guinea
1474             Ghana
1622       West Africa

Number of matching rows: 14
Min year in results: 2015
Max year in results: 2017

In [37]:
# 4.b.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run after implementation, if used)
# === CODE TYPE: SELF TESTING
# Add your additional tests here if needed:

###
### YOUR CODE HERE
###

In [38]:
# 4.b.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run only)
# === CODE TYPE: GRADED TEST 

print ("Part 4.b. - Test 1 (0.2 points) - Sanity")
print ("\t--->Testing the implementation of 'select_rows_w_vals_in_range' ...")

raise_exception=False
file_name = 'data' + os.sep + 'flavors_of_cacao.csv'
try:
    df_chocolate = load_csv(file_name)
except Exception as e:
    raise_exception=True
    print ("Cascading error: You probably have a syntax error, in a function you're depended on, we got the following exception:")
    print (str(e))
    ###
    ### AUTOGRADER TEST - DO NOT REMOVE
    ###
    if raise_exception:
        raise 

raise_exception=False        
try:
    df_passes_cond_2 = select_rows_w_vals_in_range(df_chocolate, 'Review Date', 2015, 2017)
except Exception as e:
    print ('You probably have a syntax error, we got the following exception:')
    print (str(e))
    raise 

print ("Good Job!\nYou've passed the 1st test for the 'select_rows_w_vals_in_range' function implementation :-)")

Part 4.b. - Test 1 (0.2 points) - Sanity
	--->Testing the implementation of 'select_rows_w_vals_in_range' ...
Good Job!
You've passed the 1st test for the 'select_rows_w_vals_in_range' function implementation :-)

In [39]:
# 4.b.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run only)
# === CODE TYPE: GRADED TEST 

print ("Part 4.b. - Test 2 (0.5 points)")
print ("\t--->Testing the implementation of 'select_rows_by_cell_val' and 'select_rows_w_vals_in_range' ...")

raise_exception=False
file_name = 'data' + os.sep + 'flavors_of_cacao.csv'
try:
    df_chocolate = load_csv(file_name)
except Exception as e:
    raise_exception=True
    print ("Cascading error: You probably have a syntax error, in a function you're depended on, we got the following exception:")
    print (str(e))
    ###
    ### AUTOGRADER TEST - DO NOT REMOVE
    ###
    if raise_exception:
        raise 

raise_exception=False        
try:
    df_passes_cond_1 = select_rows_by_cell_val(df_chocolate, 'Bean Type', 'Forastero')
    df_passes_cond_1_2 = select_rows_w_vals_in_range(df_passes_cond_1, 'Review Date', 2015, 2017)
except Exception as e:
    print ('You probably have a syntax error, we got the following exception:')
    print (str(e))
    raise 

try:
    num_of_rows    = get_number_of_rows(df_passes_cond_1_2)
    num_of_columns = get_number_of_columns(df_passes_cond_1_2)
    print ('Num of rows=%d' %(num_of_rows))
    print ('Num of columns=%d' %(num_of_columns))
except Exception as e:
    raise_exception=True
    print ("Cascading error: You probably have a syntax error, in a function you're depended on, we got the following exception:")
    print (str(e))
    ###
    ### AUTOGRADER TEST - DO NOT REMOVE
    ###
    if raise_exception:
        raise 
        
raise_exception=False        
assert num_of_rows==14 and num_of_columns==9, "Wrong number of rows or columns passing conditions 1, 2"

print ("Good Job!\nYou've passed the 2nd test for the 'select_rows_by_cell_val' and 'select_rows_w_vals_in_range' function implementation :-)")       

print ('First few rows of the dataframe passing the conditions:')
df_passes_cond_1_2.head()

Part 4.b. - Test 2 (0.5 points)
	--->Testing the implementation of 'select_rows_by_cell_val' and 'select_rows_w_vals_in_range' ...
Num of rows=14
Num of columns=9
Good Job!
You've passed the 2nd test for the 'select_rows_by_cell_val' and 'select_rows_w_vals_in_range' function implementation :-)
First few rows of the dataframe passing the conditions:

,Company (Maker-if known),Specific Bean Origin or Bar Name,REF,Review Date,Cocoa Percent,Company Location,Rating,Bean Type,Broad Bean Origin
43,Alexandre,"Makwale Village, Kyela",1944,2017,70%,Netherlands,3.50,Forastero,Tanzania
403,Chocolate Makers,"Congo, Gorilla bar",1530,2015,68%,Amsterdam,3.50,Forastero,Congo
521,De Villiers,Bundibugyo District,1832,2016,70%,South Africa,2.50,Forastero,Uganda
729,Georgia Ramon,ABOCFA Coop,1642,2015,70%,Germany,4.00,Forastero,Ghana
800,hello cocoa,Uganda,1458,2015,57%,U.S.A.,2.75,Forastero,Uganda

In [40]:
# 4.b.
# ------------>>>>>>>> RUN THIS CODE CELL <<<<<<<<------------
# --------  (run only)
# === CODE TYPE: GRADED TEST 

print ("Part 4.b. - Test 3 (0.6 points)")
print ("\t--->Testing the implementation of 'select_rows_by_cell_val' and 'select_rows_w_vals_in_range' ...")
print ("\n\t====> Full grading test - the following test can not be seen before submission")

###
### AUTOGRADER TEST - DO NOT REMOVE
###

Part 4.b. - Test 3 (0.6 points)
	--->Testing the implementation of 'select_rows_by_cell_val' and 'select_rows_w_vals_in_range' ...

	====> Full grading test - the following test can not be seen before submission